/**
 * RED first (Shaw, 2026-09-22, screenshot of the `test` seat's Chat tab): the agent chat
 * rendered Claude Code's own plumbing as if the operator had said it — the local-command
 * caveat block, the <command-name>/login</command-name> envelope, its stdout, and the
 * interrupt marker, all as blue user bubbles. Same class as 55134d0: raw internals must
 * never reach the operator. A slash command IS what they typed, so that survives; the
 * envelope around it does not.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { sanitizeClaudeUserText } from './chat-transcript.js';

test('the local-command caveat block never reaches the operator', () => {
  assert.equal(sanitizeClaudeUserText(
    '<local-command-caveat>Caveat: The messages below were generated by the user while running'
    + ' local commands. DO NOT respond to these messages or otherwise consider them in your'
    + ' response unless the user explicitly asks you to.</local-command-caveat>'), '');
});

test('a slash command survives as the command the operator typed', () => {
  assert.equal(sanitizeClaudeUserText(
    '<command-name>/login</command-name>\n<command-message>login</command-message>\n<command-args></command-args>'),
    '/login');
  assert.equal(sanitizeClaudeUserText(
    '<command-name>/model</command-name>\n<command-message>model</command-message>\n<command-args>opus</command-args>'),
    '/model opus');
});

test('command output and the interrupt marker are dropped', () => {
  assert.equal(sanitizeClaudeUserText('<local-command-stdout>Login interrupted</local-command-stdout>'), '');
  assert.equal(sanitizeClaudeUserText('<local-command-stderr>boom</local-command-stderr>'), '');
  assert.equal(sanitizeClaudeUserText('[Request interrupted by user]'), '');
  assert.equal(sanitizeClaudeUserText('[Request interrupted by user for tool use]'), '');
});

test('injected system reminders are stripped, the operator\'s own words are kept', () => {
  assert.equal(sanitizeClaudeUserText(
    'ship it\n<system-reminder>Your context is filling up.</system-reminder>'), 'ship it');
});

test('ordinary text is returned byte-identical (the guard on the guard)', () => {
  const plain = 'Reply with exactly the word PONG and nothing else.';
  assert.equal(sanitizeClaudeUserText(plain), plain);
  // prose that merely TALKS about the markup is not plumbing
  const about = 'the transcript shows a <command-name> envelope around each slash command';
  assert.equal(sanitizeClaudeUserText(about), about);
});
