#!/usr/bin/env node
/**
 * F0 codegen — transcript.v2.schema.json -> TS types + Swift Codable.
 *
 * THE anti-drift mechanism: both clients' types are emitted from the ONE
 * schema. Zero dependencies, fully deterministic. Usage:
 *
 *   node codegen.mjs           # (re)write gen/transcript.gen.ts + gen/TranscriptContract.gen.swift
 *   node codegen.mjs --check   # exit 1 if committed gen/ differs from a fresh regeneration (CI)
 *
 * The Swift file's canonical copy lives HERE (gen/); the iOS repo
 * (watch-approval-app Sources/Shared/) carries a byte-identical synced copy,
 * verified by its Scripts/check-transcript-contract.sh.
 *
 * Supported schema subset (all this contract uses): objects with properties/
 * required, const (string|int), enum, string|integer|boolean, ["T","null"],
 * $ref, arrays of $ref, free-form objects, oneOf discriminated on `kind`.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const SCHEMA_PATH = join(HERE, 'transcript.v2.schema.json');
const GEN_DIR = join(HERE, 'gen');
const TS_OUT = join(GEN_DIR, 'transcript.gen.ts');
const SWIFT_OUT = join(GEN_DIR, 'TranscriptContract.gen.swift');

const schema = JSON.parse(readFileSync(SCHEMA_PATH, 'utf-8'));
const defs = schema.$defs;
const HEADER = `GENERATED by contract/transcript/codegen.mjs from transcript.v2.schema.json — DO NOT EDIT.
Edit the schema, run \`node contract/transcript/codegen.mjs\`, and commit both.
Chat contract grammar_version ${schema.properties.grammar_version.const}. Unknown item kinds MUST degrade gracefully (never mis-parse).`;

const refName = (ref) => ref.split('/').pop();
const isUnion = (def) => Array.isArray(def.oneOf);

// ---------------------------------------------------------------- TS ------
function tsType(prop) {
  if (prop.$ref) return refName(prop.$ref);
  if (prop.const !== undefined) return typeof prop.const === 'string' ? `'${prop.const}'` : String(prop.const);
  if (prop.enum) return prop.enum.map((v) => `'${v}'`).join(' | ');
  if (Array.isArray(prop.type)) return prop.type.map((t) => tsScalar(t)).join(' | ');
  if (prop.type === 'array') return `${tsType(prop.items)}[]`;
  if (prop.type === 'object' && !prop.properties) return 'Record<string, unknown>';
  return tsScalar(prop.type);
}
function tsScalar(t) {
  return { string: 'string', integer: 'number', number: 'number', boolean: 'boolean', null: 'null' }[t] || 'unknown';
}

function genTS() {
  const out = [];
  out.push('/**');
  for (const l of HEADER.split('\n')) out.push(` * ${l}`);
  out.push(' */');
  out.push('');
  out.push(`export const GRAMMAR_VERSION = ${schema.properties.grammar_version.const} as const;`);
  out.push('');
  for (const [name, def] of Object.entries(defs)) {
    if (isUnion(def)) {
      out.push(`export type ${name} =`);
      out.push(def.oneOf.map((r) => `  | ${refName(r.$ref)}`).join('\n') + ';');
    } else {
      const req = new Set(def.required || []);
      out.push(`export interface ${name} {`);
      for (const [p, prop] of Object.entries(def.properties)) {
        out.push(`  ${p}${req.has(p) ? '' : '?'}: ${tsType(prop)};`);
      }
      out.push('}');
    }
    out.push('');
  }
  const req = new Set(schema.required || []);
  out.push(`export interface ${schema.title} {`);
  for (const [p, prop] of Object.entries(schema.properties)) {
    out.push(`  ${p}${req.has(p) ? '' : '?'}: ${tsType(prop)};`);
  }
  out.push('}');
  out.push('');
  return out.join('\n');
}

// ------------------------------------------------------------- Swift ------
function swiftType(prop) {
  if (prop.$ref) return refName(prop.$ref);
  if (prop.const !== undefined) return typeof prop.const === 'string' ? 'String' : 'Int';
  if (prop.enum) return 'String';
  if (Array.isArray(prop.type)) return swiftScalar(prop.type.find((t) => t !== 'null'));
  if (prop.type === 'array') return `[${swiftType(prop.items)}]`;
  if (prop.type === 'object' && !prop.properties) return '[String: JSONValue]';
  return swiftScalar(prop.type);
}
function swiftScalar(t) {
  return { string: 'String', integer: 'Int', number: 'Double', boolean: 'Bool' }[t] || 'JSONValue';
}
const isNullable = (prop) => Array.isArray(prop.type) && prop.type.includes('null');

function swiftStruct(name, def) {
  const req = new Set(def.required || []);
  const out = [`struct ${name}: Codable, Equatable {`];
  for (const [p, prop] of Object.entries(def.properties)) {
    const optional = !req.has(p) || isNullable(prop);
    out.push(`    let ${p}: ${swiftType(prop)}${optional ? '?' : ''}`);
  }
  out.push('}');
  return out.join('\n');
}

function swiftUnion(name, def) {
  const variants = def.oneOf.map((r) => refName(r.$ref)).map((t) => ({
    type: t,
    kind: defs[t].properties.kind.const,
    caseName: defs[t].properties.kind.const.replace(/_([a-z])/g, (_, c) => c.toUpperCase()),
  }));
  const out = [];
  out.push(`/// Discriminated on \`kind\`. Unknown kinds decode to .unknown (graceful degradation).`);
  out.push(`enum ${name}: Codable, Equatable {`);
  for (const v of variants) out.push(`    case ${v.caseName}(${v.type})`);
  out.push('    case unknown');
  out.push('');
  out.push('    private enum KindKey: String, CodingKey { case kind }');
  out.push('');
  out.push('    init(from decoder: Decoder) throws {');
  out.push('        let c = try decoder.container(keyedBy: KindKey.self)');
  out.push('        switch try c.decode(String.self, forKey: .kind) {');
  for (const v of variants) {
    out.push(`        case "${v.kind}": self = .${v.caseName}(try ${v.type}(from: decoder))`);
  }
  out.push('        default: self = .unknown');
  out.push('        }');
  out.push('    }');
  out.push('');
  out.push('    func encode(to encoder: Encoder) throws {');
  out.push('        switch self {');
  for (const v of variants) out.push(`        case .${v.caseName}(let v): try v.encode(to: encoder)`);
  out.push('        case .unknown: break');
  out.push('        }');
  out.push('    }');
  out.push('}');
  return out.join('\n');
}

const SWIFT_JSONVALUE = `/// Any JSON value (free-form tool args). Lenient + lossless.
indirect enum JSONValue: Codable, Equatable {
    case string(String)
    case number(Double)
    case bool(Bool)
    case null
    case array([JSONValue])
    case object([String: JSONValue])

    init(from decoder: Decoder) throws {
        let c = try decoder.singleValueContainer()
        if c.decodeNil() { self = .null }
        else if let b = try? c.decode(Bool.self) { self = .bool(b) }
        else if let n = try? c.decode(Double.self) { self = .number(n) }
        else if let s = try? c.decode(String.self) { self = .string(s) }
        else if let a = try? c.decode([JSONValue].self) { self = .array(a) }
        else if let o = try? c.decode([String: JSONValue].self) { self = .object(o) }
        else { self = .null }
    }

    func encode(to encoder: Encoder) throws {
        var c = encoder.singleValueContainer()
        switch self {
        case .string(let v): try c.encode(v)
        case .number(let v): try c.encode(v)
        case .bool(let v): try c.encode(v)
        case .null: try c.encodeNil()
        case .array(let v): try c.encode(v)
        case .object(let v): try c.encode(v)
        }
    }

    var stringValue: String? { if case .string(let v) = self { return v }; return nil }
}`;

function genSwift() {
  const out = [];
  for (const l of HEADER.split('\n')) out.push(`// ${l}`);
  out.push('');
  out.push('import Foundation');
  out.push('');
  out.push(`let TRANSCRIPT_GRAMMAR_VERSION = ${schema.properties.grammar_version.const}`);
  out.push('');
  out.push(SWIFT_JSONVALUE);
  out.push('');
  for (const [name, def] of Object.entries(defs)) {
    out.push(isUnion(def) ? swiftUnion(name, def) : swiftStruct(name, def));
    out.push('');
  }
  out.push(swiftStruct(schema.title, schema));
  out.push('');
  return out.join('\n');
}

// -------------------------------------------------------------- main ------
// The dashboard consumes a byte-identical synced copy inside its own src tree
// (vite/tsc root can't reach outside dashboard/), kept in lockstep by --check.
const DASHBOARD_TS_OUT = join(HERE, '..', '..', 'dashboard', 'src', 'lib', 'transcript.gen.ts');

const artifacts = [
  [TS_OUT, genTS()],
  [SWIFT_OUT, genSwift()],
  [DASHBOARD_TS_OUT, genTS()],
];

if (process.argv.includes('--check')) {
  let dirty = false;
  for (const [path, fresh] of artifacts) {
    const committed = existsSync(path) ? readFileSync(path, 'utf-8') : null;
    if (committed !== fresh) {
      dirty = true;
      console.error(`DRIFT: ${path} does not match regeneration from the schema.`);
    }
  }
  if (dirty) {
    console.error('Run `node contract/transcript/codegen.mjs` and commit the result.');
    process.exit(1);
  }
  console.log('codegen --check: gen/ artifacts match the schema.');
} else {
  mkdirSync(GEN_DIR, { recursive: true });
  for (const [path, fresh] of artifacts) {
    writeFileSync(path, fresh);
    console.log(`wrote ${path}`);
  }
}
