"""Write contract/pair-token-cases.json from scripts/pairing.py.

The Mac and iOS pairing parsers are tested against this file, so every "expect" in it is
what parse_pair_input returns TODAY. scripts/test_pairing.py fails if the file on disk differs
from what this script would write. After changing the parser:

    python3 scripts/gen_pair_token_cases.py
"""
import base64
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from scripts.pairing import MAX_PAIR_INPUT, PAIR_TOKEN_PREFIX, pair_token, parse_pair_input  # noqa: E402

OUT = Path(__file__).resolve().parent.parent / "contract" / "pair-token-cases.json"
CODE = "Xq3v-9Kd_Lm2pR7sT0aB"
HOST = "https://box.tail1234.ts.net:8443"


def _wrap(obj):
    raw = json.dumps(obj, separators=(",", ":")).encode()
    return PAIR_TOKEN_PREFIX + base64.urlsafe_b64encode(raw).decode().rstrip("=")


def build():
    tok = pair_token(CODE, HOST)
    body = tok[len(PAIR_TOKEN_PREFIX):]
    padded = PAIR_TOKEN_PREFIX + base64.urlsafe_b64encode(
        json.dumps({"code": CODE, "base_url": HOST}, separators=(",", ":")).encode()).decode()
    rows = [
        # what `orchestra pair` prints
        ("token, tailnet https with port", tok, (CODE, HOST)),
        ("token, https without port", pair_token(CODE, "https://box.tail1234.ts.net"), None),
        ("token, loopback", pair_token("a1", "https://127.0.0.1:8443"), None),
        # what a paste does to it
        ("token with surrounding whitespace", "  " + tok + "\n", None),
        ("token wrapped across lines by an 80-column terminal", tok[:45] + "\n" + tok[45:90] + "\r\n" + tok[90:], None),
        ("token with = padding kept", padded, None),
        # legacy and bare
        ("legacy compact JSON line", json.dumps({"code": CODE, "base_url": HOST}, separators=(",", ":")), None),
        ("legacy JSON with spaces and a trailing newline", json.dumps({"code": CODE, "base_url": HOST}) + "\n", None),
        ("legacy JSON with padded fields (trimmed)", json.dumps({"code": " " + CODE + " ", "base_url": " " + HOST + " "}), None),
        ("uppercase HTTPS scheme is https", _wrap({"code": CODE, "base_url": "HTTPS://box.tail1234.ts.net:8443"}), None),
        ("bare legacy code", CODE, None),
        ("bare code with surrounding whitespace", "\t" + CODE + " \n", None),
        # falls through to a bare code (urlsafe alphabet, so it might be one)
        ("uppercase prefix is not the token prefix -> bare", "ORC1_" + body, None),
        ("token decoding to {} -> bare", _wrap({}), None),
        ("token whose base_url is http -> bare", _wrap({"code": "c", "base_url": "http://box"}), None),
        ("token whose base_url has no host -> bare", _wrap({"code": "c", "base_url": "https://:443"}), None),
        ("token decoding to a JSON array -> bare", _wrap(["a"]), None),
        ("token whose code has a space -> bare", _wrap({"code": "a b", "base_url": HOST}), None),
        ("token body with length % 4 == 1 -> bare", PAIR_TOKEN_PREFIX + "abcde", None),
        # not a pairing code at all
        ("empty", "", None),
        ("whitespace only", "  \n ", None),
        ("bare code with a space inside -> null", "abc def", None),
        ("token with a non-base64 character -> null", PAIR_TOKEN_PREFIX + "abc!def", None),
        ("legacy JSON with http base_url -> null", json.dumps({"code": "c", "base_url": "http://box"}), None),
        ("non-ASCII bare code -> null", "código", None),
        ("longer than the input cap -> null", PAIR_TOKEN_PREFIX + "A" * MAX_PAIR_INPUT, None),
    ]
    cases = []
    for name, inp, produced in rows:
        case = {"name": name, "input": inp}
        if produced:
            case.update(produced_by="pair_token", code=produced[0], base_url=produced[1])
        case["expect"] = parse_pair_input(inp)
        cases.append(case)
    return {
        "_about": "GENERATED by scripts/gen_pair_token_cases.py from scripts/pairing.py "
                  "(pair_token, parse_pair_input); scripts/test_pairing.py fails if this file "
                  "drifts. Rules: see parse_pair_input. expect null = not a pairing code. "
                  "The producer never emits duplicate JSON keys; their handling is unspecified.",
        "prefix": PAIR_TOKEN_PREFIX,
        "max_input": MAX_PAIR_INPUT,
        "cases": cases,
    }


def render():
    return json.dumps(build(), indent=2, ensure_ascii=False) + "\n"


if __name__ == "__main__":
    OUT.write_text(render())
    print(f"wrote {OUT} ({len(build()['cases'])} cases)")
