/**
 * GENERATED by contract/transcript/codegen.mjs from transcript.v2.schema.json — DO NOT EDIT.
 * Edit the schema, run `node contract/transcript/codegen.mjs`, and commit both.
 * Chat contract grammar_version 2. Unknown item kinds MUST degrade gracefully (never mis-parse).
 */

export const GRAMMAR_VERSION = 2 as const;

export type ChatItem =
  | TextItem
  | ThinkingItem
  | ToolUseItem
  | ToolResultItem
  | QueuedBatchItem;

export interface TextItem {
  kind: 'text';
  role: 'user' | 'assistant';
  text: string;
  is_system?: boolean;
  queued?: boolean;
  ts?: string;
  uuid?: string;
}

export interface ThinkingItem {
  kind: 'thinking';
  role: 'assistant';
  text: string;
  ts?: string;
  uuid?: string;
}

export interface ToolUseItem {
  kind: 'tool_use';
  role: 'assistant';
  tool: string;
  input: Record<string, unknown>;
  summary: string;
  input_full?: string;
  id?: string;
  ts?: string;
  uuid?: string;
}

export interface ToolResultItem {
  kind: 'tool_result';
  role: 'user';
  text: string;
  tool_use_id?: string;
  is_error?: boolean;
  ts?: string;
  uuid?: string;
}

export interface BatchEntry {
  agent: string;
  sent_ts: string;
  body: string;
}

export interface QueuedBatchItem {
  kind: 'queued_batch';
  count: number;
  entries: BatchEntry[];
  ts?: string;
  key: string;
}

export type RenderItem =
  | RenderUser
  | RenderAssistant
  | RenderThinking
  | RenderTool
  | RenderQueuedBatch;

export interface RenderUser {
  kind: 'user';
  text: string;
  is_system?: boolean;
  queued?: boolean;
  ts?: string;
  key: string;
}

export interface RenderAssistant {
  kind: 'assistant';
  text: string;
  ts?: string;
  key: string;
}

export interface RenderThinking {
  kind: 'thinking';
  text: string;
  ts?: string;
  key: string;
}

export interface RenderTool {
  kind: 'tool';
  tool: string;
  summary: string;
  input: Record<string, unknown>;
  input_full?: string;
  result?: string;
  is_error?: boolean;
  ts?: string;
  key: string;
}

export interface RenderQueuedBatch {
  kind: 'queued_batch';
  count: number;
  entries: BatchEntry[];
  ts?: string;
  key: string;
}

export interface TranscriptEnvelope {
  agent_id: string;
  session_id: string | null;
  grammar_version: 2;
  items: ChatItem[];
  render_items: RenderItem[];
  error?: string;
}
